-- Create a table for storing leads
create table public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text,
  source text default 'portfolio-form',
  company text
);

-- Set up Row Level Security (RLS)
-- Enable RLS
alter table public.leads enable row level security;

-- Create a policy that allows the service role (backend) to insert/select/update/delete
-- Since we are using the service role key in the API function, it bypasses RLS by default,
-- but it's good practice to have RLS enabled for public access control.

-- Allow read access only to authenticated users (if you have an admin dashboard later)
create policy "Enable read access for authenticated users only"
on public.leads for select
to authenticated
using (true);

-- Allow insert access to anyone (public) if you were using client-side submission,
-- BUT since we are using server-side submission with Service Role Key, 
-- we don't technically need a public insert policy. 
-- However, if you switch to client-side later:
-- create policy "Enable insert for everyone" on public.leads for insert with check (true);
